# Generated by Django 5.2.7 on 2025-10-02 11:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order_id', models.CharField(db_index=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_id', models.CharField(db_index=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(choices=[('email', 'Email'), ('upload', 'Manual Upload'), ('api', 'API')], default='email', max_length=20)),
                ('source_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('compared_payload', models.JSONField(blank=True, null=True)),
                ('document_container', models.CharField(blank=True, max_length=100, null=True)),
                ('document_blob_path', models.CharField(blank=True, max_length=512, null=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoice_gate.purchaseorderref')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('mismatched', 'Mismatched'), ('error', 'Error')], db_index=True, default='pending', max_length=20)),
                ('summary', models.TextField(blank=True, null=True)),
                ('mismatch_count', models.PositiveIntegerField(default=0)),
                ('matched_item_count', models.PositiveIntegerField(default=0)),
                ('quantities_ok', models.BooleanField(default=True)),
                ('prices_ok', models.BooleanField(default=True)),
                ('totals_ok', models.BooleanField(default=True)),
                ('currency_ok', models.BooleanField(default=True)),
                ('linkage_ok', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('po_snapshot', models.JSONField(blank=True, null=True)),
                ('invoice_snapshot', models.JSONField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_runs', to='invoice_gate.invoiceref')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_runs', to='invoice_gate.purchaseorderref')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationItemResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('inv_original_name', models.CharField(blank=True, max_length=500, null=True)),
                ('po_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('po_unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('invoice_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('invoice_unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_match', models.BooleanField(default=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_results', to='invoice_gate.verificationrun')),
            ],
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('header', 'Header'), ('item', 'Item'), ('total', 'Total')], default='item', max_length=10)),
                ('type', models.CharField(choices=[('missing_item', 'Missing Item'), ('extra_item', 'Extra Item'), ('quantity_mismatch', 'Quantity Mismatch'), ('price_mismatch', 'Price Mismatch'), ('tax_mismatch', 'Tax Mismatch'), ('subtotal_mismatch', 'Subtotal Mismatch'), ('total_mismatch', 'Grand Total Mismatch'), ('currency_mismatch', 'Currency Mismatch'), ('po_link_mismatch', 'PO Link Mismatch')], max_length=30)),
                ('field', models.CharField(blank=True, max_length=50, null=True)),
                ('expected', models.CharField(blank=True, max_length=100, null=True)),
                ('actual', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('item_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='invoice_gate.verificationitemresult')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='invoice_gate.verificationrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='invoiceref',
            index=models.Index(fields=['invoice_id'], name='invoice_gat_invoice_2eefa7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceref',
            index=models.Index(fields=['source_type', 'source_ref'], name='invoice_gat_source__e0e788_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrun',
            index=models.Index(fields=['status'], name='invoice_gat_status_4299ff_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrun',
            index=models.Index(fields=['created_at'], name='invoice_gat_created_5f9844_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationitemresult',
            index=models.Index(fields=['item_id'], name='invoice_gat_item_id_0af426_idx'),
        ),
        migrations.AddIndex(
            model_name='discrepancy',
            index=models.Index(fields=['level', 'type'], name='invoice_gat_level_192c39_idx'),
        ),
    ]
