# Generated by Django 5.2.7 on 2025-10-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_gate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderref',
            name='purchase_order_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
