# Generated by Django 5.2.7 on 2025-10-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_gate', '0002_alter_purchaseorderref_purchase_order_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceRef',
            new_name='Invoice',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoice_gat_invoice_de1e64_idx',
            old_name='invoice_gat_invoice_2eefa7_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoice_gat_source__32304a_idx',
            old_name='invoice_gat_source__e0e788_idx',
        ),
    ]
