# Generated by Django 5.2.7 on 2025-10-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_gate', '0003_rename_invoiceref_invoice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseOrderRef',
            new_name='PurchaseOrder',
        ),
    ]
