# Generated by Django 5.2.7 on 2025-10-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_gate', '0004_rename_purchaseorderref_purchaseorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerificationItemResult',
            new_name='ItemVerification',
        ),
        migrations.RenameIndex(
            model_name='itemverification',
            new_name='invoice_gat_item_id_5b4767_idx',
            old_name='invoice_gat_item_id_0af426_idx',
        ),
    ]
